### ISSUE TITLE
DateTime Picker not working on date-only="false" case

### ISSUE THREAD

**Issue by DILEEPKUMAREBIX** [ng2-ui/ng2-datetime-picker#13] opened 2016-08-24 11:13 UTC
I tried ng2-datetime-picker today, its not working properly with date-only="false" condition and its working in date-only="true"

Following i have used in my template
"<input [(ngModel)]="date1" datetime-picker  />"  --> Not working as shown in image

<input [(ngModel)]="date1" datetime-picker date-only="false" />   --> even i set 'date-only' to false, i am getting only date picker.

![issue](https://cloud.githubusercontent.com/assets/16190934/17928681/7ae79380-6a19-11e6-8bfa-e76128d2db08.png)

![issue](https://cloud.githubusercontent.com/assets/16190934/17928599/1d026d80-6a19-11e6-910c-3b1e08e65aeb.png)

**Comment by allenhwkim** [comment] 2016-08-24 12:43
Thanks for using this module.
Have you tried plnkr example working on your browser?

This is date parsing error. I don't know the cause yet. It happened on Windows environments but I made a fix. it's interesting to see it again.

**Comment by DILEEPKUMAREBIX** [comment] 2016-08-25 05:10
Thanks for your response.
I tried plnkr but its not working here, i just used it in my project using npm install instructions.
Its working fine with date-only but facing the problem if i remove the same attribute(default date-only="false" righ?).

**Comment by DILEEPKUMAREBIX** [comment] 2016-08-25 11:37
https://ng2-ui.github.io/#/datetime-picker

Here it is working fine, but i don't know why it is now working in my personal project. I gone through the code and it is failing at formatting...

**Comment by allenhwkim** [comment] 2016-08-25 12:38
Rectently upgradad to RC5. https://plnkr.co/edit/A5ITtI?p=info
Can you reproduce your issue with this plnkr?

**Comment by DILEEPKUMAREBIX** [comment] 2016-08-25 13:07
![issue](https://cloud.githubusercontent.com/assets/16190934/17970119/d1278816-6af2-11e6-8812-70711a2951f3.png)

![issue1](https://cloud.githubusercontent.com/assets/16190934/17970149/ee2ac220-6af2-11e6-8db7-f8f961ed9268.png)


Getting like above... Please check
May i know reason for problem?

**Comment by allenhwkim** [comment] 2016-08-25 13:18
Please fork and save then paste the url

**Comment by allenhwkim** [comment] 2016-09-21 13:57
@nickthakkar please test this after you successfully build a plnkr

**Comment by allenhwkim** [comment] 2016-09-22 20:25
This has been fixed with the release of 0.9.0. Please test

**Comment by allenhwkim** [comment] 2016-09-22 21:01
Closing now. If not works, please reopen this issue.

**Closed by allenhwkim** 2016-09-22 21:01 UTC
